### ISSUE TITLE
[Bug][3.0.1] Save state preview no longer matches console aspect ratio

### ISSUE THREAD

**Issue by phuzybuny** [LoveRetro/NextUI#227]
The Save state preview (both for Save and Load) appears to be wide screen for all consoles on the TSP. Previously it would match the console aspect ratio. The issue also exists in release version 3.0.0.

**Comment by ro8inmorgan** [comment]
This should be fixed can you confirm/

**Comment by phuzybuny** [comment]
The issue persists on 3.0.3. 

I should clarify that I am refering to the in-game menu Save/Load save state preview.

![Image](https://github.com/user-attachments/assets/679f950b-4f68-45cb-9aff-0972ca7cd2c6)

**Comment by laesetuc** [comment]
This seems to be fixed now!  On 4.3.0 at least!

**Comment by phuzybuny** [comment]
Issue persists for me on 4.3.5.

**Comment by phuzybuny** [comment]
Issue appears to be fixed on 4.3.10 but only after saving a new save state (existing save state previous retain the incorrect aspect ratio).

**Comment by ro8inmorgan** [comment]
Yes thats normal it has to generate a new screenshot with the fix :)
